
name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build WAR
      run: mvn clean package

    - name: Deploy to Tomcat server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.TOMCAT_HOST }}
        username: ${{ secrets.TOMCAT_USER }}
        password: ${{ secrets.TOMCAT_PASS }}
        source: target/*.war
        target: /opt/tomcat/webapps
